name: Pixee PR Action

on:
  pull_request:
    branches:
      - master

jobs:
  pixee:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Pixee
      uses: docker://codemodder/pixee-cli
      with:
        args: "pixee fix ."
